import { EquipmentAttackType, type WeaponTableData } from "@/types/db-types";

export const tableData_Weapon: WeaponTableData[] = [
  {
    name: ['刀', '剑'],
    power: 100,
    effectiveInterval: 1000,
    attackType: EquipmentAttackType.sword,
    description: '只是普通的刀',
    lifeSteal: 0,
    accumulatedValue_Fire: 0,
    accumulatedValue_Ice: 0,
    accumulatedValue_Bleeding: 0,
  },
  {
    name: '偃月刀',
    power: 200,
    effectiveInterval: 800,
    attackType: EquipmentAttackType.sword,
    description: '偃月刀',
    lifeSteal: 0,
    accumulatedValue_Fire: 0,
    accumulatedValue_Ice: 0,
    accumulatedValue_Bleeding: 0,
  },
  {
    name: '青龙偃月刀',
    power: 300,
    effectiveInterval: 600,
    attackType: EquipmentAttackType.sword,
    description: '大名鼎鼎的青龙偃月刀',
    lifeSteal: 0,
    accumulatedValue_Fire: 100,
    accumulatedValue_Ice: 0,
    accumulatedValue_Bleeding: 0,
  },
  {
    name: '妖刀',
    power: 20,
    effectiveInterval: 300,
    attackType: EquipmentAttackType.sword,
    description: '妖刀',
    lifeSteal: 50,
    accumulatedValue_Fire: 0,
    accumulatedValue_Ice: 0,
    accumulatedValue_Bleeding: 30,
  },
  {
    name: '村正妖刀',
    power: 40,
    effectiveInterval: 240,
    attackType: EquipmentAttackType.sword,
    description: '大名鼎鼎的村正妖刀',
    lifeSteal: 200,
    accumulatedValue_Fire: 0,
    accumulatedValue_Ice: 0,
    accumulatedValue_Bleeding: 50,
  },
  {
    name: '棍',
    power: 40,
    effectiveInterval: 2000,
    attackType: EquipmentAttackType.stick,
    description: '只是普通的棍',
    lifeSteal: 0,
    accumulatedValue_Fire: 0,
    accumulatedValue_Ice: 0,
    accumulatedValue_Bleeding: 0,
  },
  {
    name: '弓',
    power: 80,
    effectiveInterval: 1600,
    attackType: EquipmentAttackType.bow,
    description: '只是普通的弓',
    lifeSteal: 0,
    accumulatedValue_Fire: 0,
    accumulatedValue_Ice: 0,
    accumulatedValue_Bleeding: 0,
  },
  {
    name: '矛',
    power: 100,
    effectiveInterval: 1200,
    attackType: EquipmentAttackType.spear,
    description: '只是普通的矛',
    lifeSteal: 0,
    accumulatedValue_Fire: 0,
    accumulatedValue_Ice: 0,
    accumulatedValue_Bleeding: 0,
  },
  {
    name: '蛇矛',
    power: 200,
    effectiveInterval: 2000,
    attackType: EquipmentAttackType.spear,
    description: '蛇矛',
    lifeSteal: 0,
    accumulatedValue_Fire: 0,
    accumulatedValue_Ice: 0,
    accumulatedValue_Bleeding: 0,
  },
  {
    name: '丈八蛇矛',
    power: 400,
    effectiveInterval: 1500,
    attackType: EquipmentAttackType.spear,
    description: '大名鼎鼎的丈八蛇矛',
    lifeSteal: 0,
    accumulatedValue_Fire: 0,
    accumulatedValue_Ice: 100,
    accumulatedValue_Bleeding: 0,
  },
  {
    name: '斧',
    power: 60,
    effectiveInterval: 1600,
    attackType: EquipmentAttackType.axe,
    description: '只是普通的斧',
    lifeSteal: 0,
    accumulatedValue_Fire: 0,
    accumulatedValue_Ice: 0,
    accumulatedValue_Bleeding: 10,
  },
];

export default tableData_Weapon;