import { WeaponAttackType, type WeaponTableData } from "@/types/db-types";

export const tableData_Weapon: WeaponTableData[] = [
  {
    name: ['刀', '剑'],
    power: 100,
    effectiveInterval: 500,
    attackType: WeaponAttackType.sword,
    description: '只是普通的刀',
    lifeSteal: 0,
    accumulatedValue_Fire: 0,
    accumulatedValue_Ice: 0,
    accumulatedValue_Bleeding: 0,
  },
  {
    name: '偃月刀',
    power: 150,
    effectiveInterval: 400,
    attackType: WeaponAttackType.sword,
    description: '偃月刀',
    lifeSteal: 0,
    accumulatedValue_Fire: 0,
    accumulatedValue_Ice: 0,
    accumulatedValue_Bleeding: 0,
  },
  {
    name: '青龙偃月刀',
    power: 300,
    effectiveInterval: 300,
    attackType: WeaponAttackType.sword,
    description: '大名鼎鼎的青龙偃月刀',
    lifeSteal: 0,
    accumulatedValue_Fire: 100,
    accumulatedValue_Ice: 0,
    accumulatedValue_Bleeding: 0,
  },
  {
    name: '妖刀',
    power: 10,
    effectiveInterval: 100,
    attackType: WeaponAttackType.sword,
    description: '妖刀',
    lifeSteal: 50,
    accumulatedValue_Fire: 0,
    accumulatedValue_Ice: 0,
    accumulatedValue_Bleeding: 50,
  },
  {
    name: '村正妖刀',
    power: 20,
    effectiveInterval: 100,
    attackType: WeaponAttackType.sword,
    description: '大名鼎鼎的村正妖刀',
    lifeSteal: 200,
    accumulatedValue_Fire: 0,
    accumulatedValue_Ice: 0,
    accumulatedValue_Bleeding: 100,
  },
  {
    name: '棍',
    power: 50,
    effectiveInterval: 1000,
    attackType: WeaponAttackType.stick,
    description: '只是普通的棍',
    lifeSteal: 0,
    accumulatedValue_Fire: 0,
    accumulatedValue_Ice: 0,
    accumulatedValue_Bleeding: 0,
  },
  {
    name: '弓',
    power: 150,
    effectiveInterval: 800,
    attackType: WeaponAttackType.bow,
    description: '只是普通的弓',
    lifeSteal: 0,
    accumulatedValue_Fire: 0,
    accumulatedValue_Ice: 0,
    accumulatedValue_Bleeding: 0,
  },
  {
    name: '矛',
    power: 70,
    effectiveInterval: 600,
    attackType: WeaponAttackType.spear,
    description: '只是普通的矛',
    lifeSteal: 0,
    accumulatedValue_Fire: 0,
    accumulatedValue_Ice: 0,
    accumulatedValue_Bleeding: 0,
  },
  {
    name: '蛇矛',
    power: 100,
    effectiveInterval: 1000,
    attackType: WeaponAttackType.spear,
    description: '蛇矛',
    lifeSteal: 0,
    accumulatedValue_Fire: 0,
    accumulatedValue_Ice: 0,
    accumulatedValue_Bleeding: 0,
  },
  {
    name: '丈八蛇矛',
    power: 200,
    effectiveInterval: 500,
    attackType: WeaponAttackType.spear,
    description: '大名鼎鼎的丈八蛇矛',
    lifeSteal: 0,
    accumulatedValue_Fire: 0,
    accumulatedValue_Ice: 100,
    accumulatedValue_Bleeding: 0,
  },
  {
    name: '斧',
    power: 100,
    effectiveInterval: 800,
    attackType: WeaponAttackType.axe,
    description: '只是普通的斧',
    lifeSteal: 0,
    accumulatedValue_Fire: 0,
    accumulatedValue_Ice: 0,
    accumulatedValue_Bleeding: 0,
  },
]

export default tableData_Weapon;